version: '3.8'

services:

  # https://github.com/localstack/localstack/releases
  localstack300:
    image: localstack/localstack:3.0.0
    environment:
      - DEBUG=1
      - LS_LOG=trace
    volumes:
      - ./localstack/formation.yaml:/etc/localstack/init/ready.d/formation.yaml
      - ./localstack/init.sh:/etc/localstack/init/ready.d/init.sh
    ports:
      - "4566:4566"